# -*- coding: utf-8 -*-
"""homewo11.4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14dBIyHhLYKC-uHG2QDoWMSZjUQlewzkm
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("breast_cancer_1000_genes.tsv", sep = "\t", index_col = 0).T
df = pd.DataFrame(np.sort(df, axis=0), columns=df.columns).T # отсортировали 

df["max"] = df.max(axis=1)  # столбец с максимальными значениями
df["min"] = df.min(axis=1) # столбец с минимальными значениями
df["top10"] = df["max"] - df["min"]  # столбец с разностью
df_1 = df["top10"]

df["dis"] = df.var(axis=1) # столбец с дисперсиями
df_2 = df["dis"]

df["Q1"] = df.quantile(0.25, axis=1) # столбец с квартилем 0,25
df["Q3"] = df.quantile(0.75, axis=1) # столбец с квартилем 0,75
df["IQR"] = df["Q3"] - df["Q1"] # столбец с разностью квартилей
df_3 = df["IQR"]
# Новые датафреймы со значениями, отсортированными по возрастанию
df_1 = df_1.sort_values(axis=0)
df_2 = df_2.sort_values(axis=0)
df_3 = df_3.sort_values(axis=0)
# Новые датафреймы для топ-10 генов
df1_1 = df_1.iloc[0:10] # наименьшая разность макс и мин
df2_2 = df_2.iloc[0:10] # наименьшая дисперсия
df3_3 = df_3.iloc[0:10] # наименьший интерквартильный размах

print(df)
#создаем такую удобную штучку, чтобы сразу все 3 дф сделать
fig, axs = plt.subplots(ncols = 2, nrows = 2, figsize=(8, 8)) # несколько графиков в одном файле
axs[0][0].boxplot(df1_1) # боксплот для разности макс и мин
axs[0][1].boxplot(df2_2) # боксплот для дисперсии
axs[1][0].boxplot(df3_3) # боксплот для интерквартильного размаха   
plt.tight_layout() 
plt.savefig("picture1.pdf")