# -*- coding: utf-8 -*-
"""homewo11.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/179pQDH6N2jaBcrctZsuXxftD7WCQzYrM
"""

from scipy.stats import poisson
import numpy as np

i = 1
while i < 16: 
  data = poisson.rvs(mu=17, size=100)
  average = np.average(data) # среднее арифметическое выборки
  data = data - average # из каждого элемента выборки вычли среднее
  S2 = np.sum(data**2) / (100 - 1) # несмещенная выборочная дисперсия
  if (average - 17) < (S2 - 17):
    print ("ev") # если оценка через среднее лучше
  elif (average - 17) > (S2 - 17):
    print("dis") # если оценка через дисперсию лучше
  else:
    print("=") # если оценки равны
  i += 1
# В большинстве случаев оценка с помощью среднего точнее