# -*- coding: utf-8 -*-
"""homewo11.5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-K5zKiuTFbxE5m2V5mjytkLnkGGj4Vc8
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('breast_cancer_key_genes.tsv', sep="\t", index_col=0)

sns.kdeplot(x=df['ESR1']) # в файле синяя линия
sns.kdeplot(x=df['PGR']) # в файле оранжевая линия
plt.tight_layout()
plt.savefig('kde2.pdf')
# Три подгруппы: 1- оба гена не экпрессируются, 2 - преобладает экспрессия гена ESR1, 3- средняя экспрессия обоих генов